In [2]:
import pandas as pd
import random

In [3]:
df = pd.read_csv('../../primekg/kg/nodes.csv')
df.head()

   node_index node_id     node_type node_name node_source
0           0    9796  gene/protein    PHYHIP        NCBI
1           1    7918  gene/protein    GPANK1        NCBI
2           2    8233  gene/protein     ZRSR2        NCBI
3           3    4899  gene/protein      NRF1        NCBI
4           4    5297  gene/protein     PI4KA        NCBI

In [4]:
with open('../../primekg/kg/entity2id.txt', 'w') as f:
    f.write(f'{len(df)}\n')
    for _, row in df.iterrows():
        f.write(f'{row["node_name"]}:{row["node_type"]}\t{row["node_index"]}\n')

In [5]:
df = pd.read_csv('../../primekg/kg/edges.csv')
df.head()

          relation display_relation  x_index  y_index
0  protein_protein              ppi        0     8889
1  protein_protein              ppi        1     2798
2  protein_protein              ppi        2     5646
3  protein_protein              ppi        3    11592
4  protein_protein              ppi        4     2122

In [6]:
relations = df.drop_duplicates(subset=['relation'])['relation'].to_list()
relation2id = {relation: i for i, relation in enumerate(relations)}

with open('../../primekg/kg/relation2id.txt', 'w') as f:
    f.write(f'{len(relations)}\n')
    for k, v in relation2id.items():
        f.write(f'{k}\t{v}\n')

In [7]:
df['rela_id'] = df['relation'].apply(lambda x: relation2id[x])
df = df[['x_index', 'y_index', 'rela_id']]
data = list(df.itertuples(index=False, name=None))
random.shuffle(data)
data[:10]

[(17707, 21352, 5),
 (58303, 69442, 28),
 (15373, 15184, 5),
 (76888, 76886, 27),
 (5270, 64485, 28),
 (3479, 50110, 18),
 (14137, 14296, 5),
 (21452, 15023, 5),
 (15635, 14976, 5),
 (15685, 15176, 5)]

In [8]:
with open('../../primekg/kg/all2id.txt', 'w') as f:
    f.write(f'{len(data)}\n')
    for x, y, r in data:
        f.write(f'{x} {y} {r}\n')

In [7]:
train_size = int(len(data) * 0.9)
valid_size = int(len(data) * 0.05)
test_size = len(data) - train_size - valid_size

print('train size: ', train_size)
print('valid size: ', valid_size)
print('test size: ', test_size)

train_data = data[:train_size]
valid_data = data[train_size:train_size+valid_size]
test_data = data[train_size+valid_size:]

train size:  7290448
valid size:  405024
test size:  405026

In [8]:
with open('../../primekg/kg/train2id.txt', 'w') as f:
    f.write(f'{len(train_data)}\n')
    for x, y, r in train_data:
        f.write(f'{x} {y} {r}\n')

In [9]:
with open('../../primekg/kg/valid2id.txt', 'w') as f:
    f.write(f'{len(valid_data)}\n')
    for x, y, r in valid_data:
        f.write(f'{x} {y} {r}\n')

In [10]:
with open('../../primekg/kg/test2id.txt', 'w') as f:
    f.write(f'{len(test_data)}\n')
    for x, y, r in test_data:
        f.write(f'{x} {y} {r}\n')