In [2]:
import pandas as pd

In [3]:
tak1 = pd.read_csv('link_result_rotate_150_kg4rd_base_TAK1_drug.csv').head(50)
tak1.head()

,head,rel,tail,score,in,head_ent,rel_ent,tail_ent,tail_id,tail_source
0,9662,1,20180,0.838419,False,MAP3K7:gene/protein,drug_protein,ATP:drug,kg4rd:DB00171,DrugBank
1,9662,1,21128,0.820538,False,MAP3K7:gene/protein,drug_protein,Phosphoaminophosphonic Acid-Adenylate Ester:drug,kg4rd:DB04395,DrugBank
2,9662,1,20422,0.811479,False,MAP3K7:gene/protein,drug_protein,Phenethyl Isothiocyanate:drug,kg4rd:DB12695,DrugBank
3,9662,1,21391,0.788737,False,MAP3K7:gene/protein,drug_protein,Tetrabromo-2-Benzotriazole:drug,kg4rd:DB04462,DrugBank
4,9662,1,20780,0.739721,False,MAP3K7:gene/protein,drug_protein,Staurosporine:drug,kg4rd:DB02010,DrugBank

In [4]:
s1pr1 = pd.read_csv('link_result_rotate_150_kg4rd_base_S1PR1_drug.csv').head(50)
s1pr1.head()

,head,rel,tail,score,in,head_ent,rel_ent,tail_ent,tail_id,tail_source
0,5153,1,19991,0.909997,False,S1PR1:gene/protein,drug_protein,Fostamatinib:drug,kg4rd:DB12010,DrugBank
1,5153,1,21317,0.845650,False,S1PR1:gene/protein,drug_protein,Colforsin:drug,kg4rd:DB02587,DrugBank
2,5153,1,20308,0.640527,False,S1PR1:gene/protein,drug_protein,Enprofylline:drug,kg4rd:DB00824,DrugBank
3,5153,1,20322,0.373479,False,S1PR1:gene/protein,drug_protein,DPCPX:drug,kg4rd:DB12946,DrugBank
4,5153,1,20180,0.314216,False,S1PR1:gene/protein,drug_protein,ATP:drug,kg4rd:DB00171,DrugBank

In [5]:
set(tak1['tail_ent'].tolist()) & set(s1pr1['tail_ent'].tolist())

{'ATP:drug',
 'Artenimol:drug',
 'Copper:drug',
 'Dexfosfoserine:drug',
 'Fostamatinib:drug',
 'Myristic acid:drug',
 'Phosphoaminophosphonic Acid-Adenylate Ester:drug',
 'Staurosporine:drug',
 'Zinc acetate:drug'}