In [28]:
import pandas as pd

In [29]:
df = pd.read_csv('../../../data/data_synonyms/mondo_synonyms_concat.csv')
synonyms_count = df.shape[0]
node_count = df['id'].drop_duplicates().count()
print("mondo synonyms count: ", synonyms_count)
print("mondo node count: ", node_count)
print("mondo mean value: ", synonyms_count / node_count)
df.head()

mondo synonyms count:  151126
mondo node count:  29739
mondo mean value:  5.081744510575339

   id           name preferred_name
0   1        disease           True
1   1  other disease            NaN
2   1      condition            NaN
3   1      disorders            NaN
4   1       diseases            NaN

In [9]:
df = pd.read_csv('../../../data/data_synonyms/drugbank_synonyms_concat.csv')
synonyms_count = df.shape[0]
node_count = df['id'].drop_duplicates().count()
print("drugbank synonyms count: ", synonyms_count)
print("drugbank node count: ", node_count)
print("drugbank mean value: ", synonyms_count / node_count)
df.head()

drugbank synonyms count:  64187
drugbank node count:  17430
drugbank mean value:  3.682558806655192

        id                            name preferred_name
0  DB00001                       lepirudin           True
1  DB00001  [leu1, thr2]-63-desulfohirudin            NaN
2  DB00001                desulfatohirudin            NaN
3  DB00001               hirudin variant-1            NaN
4  DB00001           lepirudin recombinant            NaN

In [17]:
df = pd.read_csv('../../../data/data_synonyms/go_synonyms.csv')
synonyms_count = df.shape[0]
node_count = df['id'].drop_duplicates().count()
print("go synonyms count: ", synonyms_count)
print("go node count: ", node_count)
print("go mean value: ", synonyms_count / node_count)
df.head()

go synonyms count:  177151
go node count:  48030
go mean value:  3.6883406204455547

   id                                name preferred_name
0   1           mitochondrion inheritance           True
1   1           mitochondrial inheritance            NaN
2   2    mitochondrial genome maintenance           True
3   3               obsolete reproduction           True
4   3  reproductive physiological process            NaN

In [18]:
df = pd.read_csv('../../../data/data_synonyms/hpo_synonyms.csv')
synonyms_count = df.shape[0]
node_count = df['id'].drop_duplicates().count()
print("hpo synonyms count: ", synonyms_count)
print("hpo node count: ", node_count)
print("hpo mean value: ", synonyms_count / node_count)
df.head()

hpo synonyms count:  42406
hpo node count:  19650
hpo mean value:  2.1580661577608145

   id                           name preferred_name
0   1                            All           True
1   2     Abnormality of body height           True
2   3   Multicystic kidney dysplasia           True
3   3            Multicystic kidneys            NaN
4   3  Multicystic dysplastic kidney            NaN

In [19]:
df = pd.read_csv('../../../data/data_synonyms/uberon_synonyms.csv')
synonyms_count = df.shape[0]
node_count = df['id'].drop_duplicates().count()
print("uberon synonyms count: ", synonyms_count)
print("uberon node count: ", node_count)
print("uberon mean value: ", synonyms_count / node_count)
df.head()

uberon synonyms count:  54283
uberon node count:  15693
uberon mean value:  3.459058178805837

   id                      name preferred_name
0   0         processual entity           True
1   2            uterine cervix           True
2   2          cervix of uterus            NaN
3   2    canalis cervicis uteri            NaN
4   2  cervical canal of uterus            NaN

In [13]:
df = pd.read_csv('../../../data/data_synonyms/hgnc_synonyms.csv')
synonyms_count = df.shape[0]
node_count = df['id'].drop_duplicates().count()
print("gene synonyms count: ", synonyms_count)
print("gene node count: ", node_count)
print("gene mean value: ", synonyms_count / node_count)
df.head()

gene synonyms count:  146830
gene node count:  43680
gene mean value:  3.361492673992674

       id                    name preferred_name
0       1                    A1BG           True
1       1  alpha-1-B glycoprotein            NaN
2  503538                A1BG-AS1           True
3  503538    A1BG antisense RNA 1            NaN
4  503538              NCRNA00181            NaN

In [25]:
df = pd.read_csv('../../../data/data_synonyms/reactome_synonyms.csv')
synonyms_count = df.shape[0]
node_count = df['id'].drop_duplicates().count()
print("reactome synonyms count: ", synonyms_count)
print("reactome node count: ", node_count)
print("reactome mean value: ", synonyms_count / node_count)
df.head()

reactome synonyms count:  2996
reactome node count:  2769
reactome mean value:  1.0819790538100398

              id                                          name preferred_name
0   R-HSA-164843                        2-LTR circle formation           True
1  R-HSA-9909438   3-Methylcrotonyl-CoA carboxylase deficiency           True
2  R-HSA-9916722  3-hydroxyisobutyryl-CoA hydrolase deficiency           True
3  R-HSA-9914274                   3-methylglutaconic aciduria           True
4    R-HSA-73843    5-Phosphoribose 1-diphosphate biosynthesis           True

In [26]:
df2 = pd.read_csv('../../../data/data/kegg/drug_kegg_pathway.csv').drop('drugbank_id', axis=1).rename(
    columns={'pathway_kegg_id': 'id', 'pathway_kegg_name': 'name'}
)
df2['preferred_name'] = True
df2.drop_duplicates()
df2.head()

         id                      name  preferred_name
0  hsa00830           Retinol metabol            True
1  hsa04726           Serotonergic sy            True
2  hsa00240        Pyrimidine metabol            True
3  hsa00670  One carbon pool by folat            True
4  hsa04728           Dopaminergic sy            True

In [27]:
df = pd.concat([df, df2])
node_count = df['id'].drop_duplicates().count()
print("pathway synonyms count: ", synonyms_count)
print("pathway node count: ", node_count)
print("pathway mean value: ", synonyms_count / node_count)

pathway synonyms count:  2996
pathway node count:  2875
pathway mean value:  1.0420869565217392

In [15]:
df = pd.read_csv('../../../data/data_synonyms/ctd_synonyms.csv')
synonyms_count = df.shape[0]
node_count = df['id'].drop_duplicates().count()
print("exposure synonyms count: ", synonyms_count)
print("exposure node count: ", node_count)
print("exposure mean value: ", synonyms_count / node_count)
df.head()

exposure synonyms count:  461788
exposure node count:  179388
exposure mean value:  2.574241309340647

        id                                    name preferred_name
0  C089250                 (0.017ferrocene)amylose           True
1  C089250                (0.017 ferrocene)amylose            NaN
2  C114385                              001-C8-NBD           True
3  C114385                              001 C8 NBD            NaN
4  C114385  H-MeTyr-Arg-MeArg-D-Leu-NH(CH2)8NH-NBD            NaN