In [3]:
import pandas as pd
# 下载地址参考 https://github.com/mims-harvard/PrimeKG
# 下载后解压到项目目录下的 primgkg/kg 文件夹下
primekg = pd.read_csv('../../primekg/kg/kg.csv', low_memory=False)

In [18]:
primekg.head()

,relation,display_relation,x_index,x_id,x_type,x_name,x_source,y_index,y_id,y_type,y_name,y_source
0,protein_protein,ppi,0,9796,gene/protein,PHYHIP,NCBI,8889,56992,gene/protein,KIF15,NCBI
1,protein_protein,ppi,1,7918,gene/protein,GPANK1,NCBI,2798,9240,gene/protein,PNMA1,NCBI
2,protein_protein,ppi,2,8233,gene/protein,ZRSR2,NCBI,5646,23548,gene/protein,TTC33,NCBI
3,protein_protein,ppi,3,4899,gene/protein,NRF1,NCBI,11592,11253,gene/protein,MAN1B1,NCBI
4,protein_protein,ppi,4,5297,gene/protein,PI4KA,NCBI,2122,8601,gene/protein,RGS20,NCBI

In [31]:
primekg.shape[0] // 2 # 关系数量 (由于是无向边, 所以双向关系都保存下来了)

4050249

In [3]:
df = primekg.drop_duplicates('x_type')
print(df.shape[0]) # 实体类型数量
df[['x_type', 'x_source', 'x_name']] # 所有的实体类型

10

,x_type,x_source,x_name
0,gene/protein,NCBI,PHYHIP
321075,drug,DrugBank,Copper
3065317,effect/phenotype,HPO,Growth abnormality
3084053,disease,MONDO_grouped,osteogenesis imperfecta
3413119,biological_process,GO,negative regulation of neurotransmitter uptake
3466005,molecular_function,GO,methyltransferase activity
3479579,cellular_component,GO,cellular anatomical entity
3782161,exposure,CTD,1-hydroxyphenanthrene
3789497,pathway,REACTOME,Apoptosis
3834678,anatomy,UBERON,uterine cervix

In [16]:
primekg.drop_duplicates('x_index').shape[0] # 实体数量 (x_index 为主键)

129375

In [3]:
primekg.drop_duplicates('x_index')['x_type'].value_counts()

x_type
biological_process    28642
gene/protein          27671
disease               17080
effect/phenotype      15311
anatomy               14035
molecular_function    11169
drug                   7957
cellular_component     4176
pathway                2516
exposure                818
Name: count, dtype: int64

In [7]:
primekg.query('x_type == "cellular_component"').drop_duplicates('x_name').head(5)['x_name']

3479579                           cellular anatomical entity
3480004                                  COPI-coated vesicle
3480005                                    transport vesicle
3480008    intrinsic component of chloroplast inner membrane
3480009         integral component of plastid inner membrane
Name: x_name, dtype: object

In [8]:
primekg.query('x_type == "biological_process"').drop_duplicates('x_name').head(5)['x_name']

3413119    negative regulation of neurotransmitter uptake
3413120              negative regulation of ion transport
3413121                    regulation of serotonin uptake
3413124                    regulation of histamine uptake
3413127       negative regulation of amino acid transport
Name: x_name, dtype: object

In [6]:
df = primekg.drop_duplicates('relation')
print(df.shape[0]) # 关系类型数量
df[['relation', 'display_relation', 'x_type', 'y_type']] # 所有的关系类型

30

,relation,display_relation,x_type,y_type
0,protein_protein,ppi,gene/protein,gene/protein
321075,drug_protein,carrier,drug,gene/protein
346728,contraindication,contraindication,drug,disease
346730,indication,indication,drug,disease
347016,off-label use,off-label use,drug,disease
389359,drug_drug,synergistic interaction,drug,drug
3061987,phenotype_protein,associated with,gene/protein,effect/phenotype
3065317,phenotype_phenotype,parent-child,effect/phenotype,effect/phenotype
3084053,disease_phenotype_negative,phenotype absent,disease,effect/phenotype
3085246,disease_phenotype_positive,phenotype present,disease,effect/phenotype
3235582,disease_protein,associated with,gene/protein,disease
3315993,disease_disease,parent-child,disease,disease
3348335,drug_effect,side effect,drug,effect/phenotype
3413119,bioprocess_bioprocess,parent-child,biological_process,biological_process
3466005,molfunc_molfunc,parent-child,molecular_function,molecular_function
3479579,cellcomp_cellcomp,parent-child,cellular_component,cellular_component
3484424,molfunc_protein,interacts with,gene/protein,molecular_function
3553954,cellcomp_protein,interacts with,gene/protein,cellular_component
3637356,bioprocess_protein,interacts with,gene/protein,biological_process
3782161,exposure_protein,interacts with,exposure,gene/protein
3783373,exposure_disease,linked to,exposure,disease
3785677,exposure_exposure,parent-child,exposure,exposure
3787817,exposure_bioprocess,interacts with,exposure,biological_process
3789442,exposure_molfunc,interacts with,exposure,molecular_function
3789487,exposure_cellcomp,interacts with,exposure,cellular_component
3789497,pathway_pathway,parent-child,pathway,pathway
3792032,pathway_protein,interacts with,gene/protein,pathway
3834678,anatomy_anatomy,parent-child,anatomy,anatomy
3848710,anatomy_protein_present,expression present,gene/protein,anatomy
5366913,anatomy_protein_absent,expression absent,gene/protein,anatomy

In [19]:
primekg.query('x_type == "disease"').drop_duplicates('x_index').shape[0] # 疾病实体的数量

17080

In [24]:
primekg.query('x_type == "disease"').shape[0]  # 和疾病有关的关系的数量

341244

In [25]:
df = primekg.query('x_type == "disease"').drop_duplicates('relation')
print(df.shape[0]) # 和疾病有关的关系类型数量
df[['relation', 'display_relation', 'x_type', 'y_type']] # 和疾病有关的关系类型

8

,relation,display_relation,x_type,y_type
3084053,disease_phenotype_negative,phenotype absent,disease,effect/phenotype
3085246,disease_phenotype_positive,phenotype present,disease,effect/phenotype
3315993,disease_disease,parent-child,disease,disease
5733528,contraindication,contraindication,disease,drug
5733530,indication,indication,disease,drug
5733816,off-label use,off-label use,disease,drug
5949716,disease_protein,associated with,disease,gene/protein
6497211,exposure_disease,linked to,disease,exposure